name: release
on:
  push:
    tags:
      - "v*"
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
  unit-test:
    needs: validation
    runs-on: ubuntu-latest
    name: "Run Unit Tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      - uses: docker/setup-buildx-action@v3
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean test
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    name: "Run Integration Tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean integrationTest
  release:
    runs-on: ubuntu-latest
    needs: integration-test
    name: "Publish To Maven Central"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean build publish -x test -x integrationTest
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
