name: ci
on: [ push ]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
  unit-test:
    needs: validation
    runs-on: ubuntu-latest
    name: "Run Unit Tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      - uses: docker/setup-buildx-action@v3
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean
      - run: ./gradlew test testCodeCoverageReport
      - uses: codecov/codecov-action@v4
        with:
          directory: "./build/reports/jacoco/testCodeCoverageReport/"
          files: "./testCodeCoverageReport.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    name: "Run Integration Tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean
      - run: ./gradlew integrationTest integrationTestCodeCoverageReport
      - uses: codecov/codecov-action@v4
        with:
          directory: "./build/reports/jacoco/integrationTestCodeCoverageReport/"
          files: "./integrationTestCodeCoverageReport.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
